// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 打点配置
type MetricsConf struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Name     string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 名称
	ConfKey  string    `gorm:"column:conf_key;NOT NULL" json:"conf_key"`                             // 配置的key
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MetricsConf) TableName() string {
	return "t_metrics_conf"
}

