// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 打点统计数据
type MetricsStat struct {
	ID         uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	ConfID     uint64    `gorm:"column:conf_id;default:0;NOT NULL" json:"conf_id"`                     // 打点的ID
	Platform   string    `gorm:"column:platform;NOT NULL" json:"platform"`                             // 平台
	Week       uint      `gorm:"column:week;default:0;NOT NULL" json:"week"`                           // 上线后的周
	Year       uint      `gorm:"column:year;default:0;NOT NULL" json:"year"`                           // 年
	Month      int       `gorm:"column:month;default:0;NOT NULL" json:"month"`                         // 月
	Day        int       `gorm:"column:day;default:0;NOT NULL" json:"day"`                             // 日
	Date       time.Time `gorm:"column:date;NOT NULL" json:"date"`                                     // 日期
	Views      uint      `gorm:"column:views;default:0;NOT NULL" json:"views"`                         // 展示次数
	Clicks     uint      `gorm:"column:clicks;default:0;NOT NULL" json:"clicks"`                       // 点击次数
	UserViews  uint      `gorm:"column:user_views;default:0;NOT NULL" json:"user_views"`               // 展示用户数
	UserClicks uint      `gorm:"column:user_clicks;default:0;NOT NULL" json:"user_clicks"`             // 点击用户数
	CreateAt   time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP   string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt   time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP   string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MetricsStat) TableName() string {
	return "t_metrics_stat"
}

