// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 签到表
type Signin struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	UserID    uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 用户ID
	Day       time.Time `gorm:"column:day;NOT NULL" json:"day"`                                       // 签到日期
	Times     uint      `gorm:"column:times;default:1;NOT NULL" json:"times"`                         // 总次数
	Continued uint      `gorm:"column:continued;default:1;NOT NULL" json:"continued"`                 // 连续次数
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *Signin) TableName() string {
	return "t_signin"
}

