// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 意见反馈
type Feedback struct {
	ID            uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	UserID        uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 用户ID
	Imgs          string    `gorm:"column:imgs;NOT NULL" json:"imgs"`                                     // 图片
	Content       string    `gorm:"column:content;NOT NULL" json:"content"`                               // 发布的内容
	ReplayContent string    `gorm:"column:replay_content" json:"replay_content"`                          // 后台回复的内容
	IsReplay      int       `gorm:"column:is_replay;default:0;NOT NULL" json:"is_replay"`                 // 是否已回复
	ReplayAt      *time.Time `gorm:"column:replay_at" json:"replay_at"`                                    // 回复时间
	CreateAt      time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP      string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt      time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP      string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *Feedback) TableName() string {
	return "t_feedback"
}

