// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 用户设备信息表
type AppDevice struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	UserID    uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 用户ID
	Platform  string    `gorm:"column:platform;NOT NULL" json:"platform"`                             // 平台
	Board     string    `gorm:"column:board;NOT NULL" json:"board"`                                   // 品牌
	Channel   string    `gorm:"column:channel;NOT NULL" json:"channel"`                               // 推送通道
	Token     string    `gorm:"column:token;NOT NULL" json:"token"`                                   // TOKEN
	PushTimes uint      `gorm:"column:push_times;default:0;NOT NULL" json:"push_times"`               // 推送次数
	OsVer     string    `gorm:"column:os_ver;NOT NULL" json:"os_ver"`                                 // 系统版本
	AppVer    string    `gorm:"column:app_ver;NOT NULL" json:"app_ver"`                               // app版本
	WgtVer    string    `gorm:"column:wgt_ver;NOT NULL" json:"wgt_ver"`                               // 热更新版本
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *AppDevice) TableName() string {
	return "t_app_device"
}

