// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 代码模版表
type AppBuildTemplate struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Platform  string    `gorm:"column:platform;NOT NULL" json:"platform"`                             // 平台名称
	ModuleID  uint64    `gorm:"column:module_id;default:0;NOT NULL" json:"module_id"`                 // 模块ID
	Fname     string    `gorm:"column:fname;NOT NULL" json:"fname"`                                   // 文件名称
	Fdesc     string    `gorm:"column:fdesc;NOT NULL" json:"fdesc"`                                   // 描述
	Ftemplate string    `gorm:"column:ftemplate;NOT NULL" json:"ftemplate"`                           // 文件模版
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *AppBuildTemplate) TableName() string {
	return "t_app_build_template"
}

