CREATE TABLE `t_order` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `order_sn` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '订单编号',
    `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
    `order_type` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '订单类型，支付成功是需要回掉',
    `order_src_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '原订单ID',
    `order_name` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '订单名称',
    `total_amount` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '总金额',
    `pay_amount` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '支付金额',
    `pay_way` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '支付方式，ali_h5,ali_app,ali_pc,ali_ercode,wx_h5,wx_app,wx_mini...',
    `order_status` TINYINT NOT NULL DEFAULT 0 COMMENT '支付状态：0待支付，1已取消，10 已支付，20已退款',
    `platform_sn` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '三方支付订单号',
    `pay_at` DATETIME DEFAULT NULL COMMENT '支付成功时间',
    `refund_at` DATETIME DEFAULT NULL COMMENT '退款成功时间',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_ip` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '创建IP',
    `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_ip` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '更新IP',
    PRIMARY KEY (`id`),
    KEY `idx_user_id`(`user_id`),
    KEY `idx_type_src`(`order_type`,`order_src_id`),
    KEY `idx_create` (`create_at`),
    KEY `idx_update` (`update_at`)
) ENGINE = innodb DEFAULT CHARSET = utf8mb4 COMMENT = '订单表';