// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 配置信息表
type Config struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	ConfKey  string    `gorm:"column:conf_key;NOT NULL" json:"conf_key"`                             // 分组KEY
	GroupKey string    `gorm:"column:group_key;NOT NULL" json:"group_key"`                           // 中间key
	ItemKey  string    `gorm:"column:item_key;NOT NULL" json:"item_key"`                             // KEY
	Val      string    `gorm:"column:val;NOT NULL" json:"val"`                                       // 具体的值
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *Config) TableName() string {
	return "t_config"
}

