// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 消息内容表
type MessageContent struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Mkey     string    `gorm:"column:mkey;NOT NULL" json:"mkey"`                                     // 消息KEY
	FromID   uint64    `gorm:"column:from_id;default:0;NOT NULL" json:"from_id"`                     // 发送人
	RecvID   uint64    `gorm:"column:recv_id;default:0;NOT NULL" json:"recv_id"`                     // 接收人
	IsRead   int       `gorm:"column:is_read;default:0;NOT NULL" json:"is_read"`                     // 是否已读
	Content  string    `gorm:"column:content;NOT NULL" json:"content"`                               // 消息内容
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MessageContent) TableName() string {
	return "t_message_content"
}

