// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 消息表
type MessageUser struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	UserID   uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 用户ID
	ToID     uint64    `gorm:"column:to_id;default:0;NOT NULL" json:"to_id"`                         // 消息接收人ID
	Mkey     string    `gorm:"column:mkey;NOT NULL" json:"mkey"`                                     // 消息KEY
	UnReads  uint      `gorm:"column:un_reads;default:0;NOT NULL" json:"un_reads"`                   // 未读消息数
	LastTime int64     `gorm:"column:last_time;default:0;NOT NULL" json:"last_time"`                 // 最后消息时间
	LastUid  uint64    `gorm:"column:last_uid;default:0;NOT NULL" json:"last_uid"`                   // 最后发送人
	LastMsg  string    `gorm:"column:last_msg;NOT NULL" json:"last_msg"`                             // 最后消息摘要
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MessageUser) TableName() string {
	return "t_message_user"
}

