// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 阅读历史
type NovelReadHistory struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	UserID    uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 用户
	NovelID   uint64    `gorm:"column:novel_id;default:0;NOT NULL" json:"novel_id"`                   // 小说ID
	SectionID uint64    `gorm:"column:section_id;default:0;NOT NULL" json:"section_id"`               // 章节ID
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *NovelReadHistory) TableName() string {
	return "t_novel_read_history"
}

