// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 小说列表
type NovelSection struct {
	ID           uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	NovelID      uint64    `gorm:"column:novel_id;default:0;NOT NULL" json:"novel_id"`                   // 小说ID
	ParentID     uint64    `gorm:"column:parent_id;default:0;NOT NULL" json:"parent_id"`                 // 父章节ID
	Name         string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 名称
	SectionIndex uint      `gorm:"column:section_index;default:0;NOT NULL" json:"section_index"`         // 章节排序
	Words        uint      `gorm:"column:words;default:0;NOT NULL" json:"words"`                         // 字数
	IsPublish    int       `gorm:"column:is_publish;default:0;NOT NULL" json:"is_publish"`               // 是否发布
	IsAudit      int       `gorm:"column:is_audit;default:0;NOT NULL" json:"is_audit"`                   // 是否已经审核
	CreateAt     time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP     string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt     time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP     string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *NovelSection) TableName() string {
	return "t_novel_section"
}

