// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 提现记录
type NovelTxLog struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	UserID   uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 用户
	Date     time.Time `gorm:"column:date;NOT NULL" json:"date"`                                     // 申请日期
	Status   int       `gorm:"column:status;default:0;NOT NULL" json:"status"`                       // 0申请中，10已审核，20完成
	PayAt    time.Time `gorm:"column:pay_at" json:"pay_at"`                                          // 支付日期
	Amount   uint      `gorm:"column:amount;default:0;NOT NULL" json:"amount"`                       // 申请提现金额
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *NovelTxLog) TableName() string {
	return "t_novel_tx_log"
}

