// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 应用版本
type AppVer struct {
	ID         uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	AppVer     string    `gorm:"column:app_ver;NOT NULL" json:"app_ver"`                               // 版本
	ApkUrl     string    `gorm:"column:apk_url;NOT NULL" json:"apk_url"`                               // android 下载地址
	WgtUrl     string    `gorm:"column:wgt_url;NOT NULL" json:"wgt_url"`                               // 热更新下载地址
	VerContent string    `gorm:"column:ver_content;NOT NULL" json:"ver_content"`                       // 版本描述
	IsOnline   int       `gorm:"column:is_online;default:0;NOT NULL" json:"is_online"`                 // 是否上架
	CreateAt   time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP   string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt   time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP   string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *AppVer) TableName() string {
	return "t_app_ver"
}

