// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 上传文件
type UploadFile struct {
	ID          uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	FileKey     string    `gorm:"column:file_key;NOT NULL" json:"file_key"`                             // 文件MD5
	FileName    string    `gorm:"column:file_name;NOT NULL" json:"file_name"`                           // 文件名称
	FileSize    uint      `gorm:"column:file_size;default:0;NOT NULL" json:"file_size"`                 // 文件大小
	Url         string    `gorm:"column:url;NOT NULL" json:"url"`                                       // 文件地址
	UploadTimes uint      `gorm:"column:upload_times;default:1;NOT NULL" json:"upload_times"`           // 上传次数
	CreateAt    time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP    string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt    time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP    string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *UploadFile) TableName() string {
	return "t_upload_file"
}

