// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 动态表
type Feed struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	UserID   uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 发布人ID
	FeedType int       `gorm:"column:feed_type;default:0;NOT NULL" json:"feed_type"`                 // 类型，0blog,10投票,11多选投票
	Title    string    `gorm:"column:title;NOT NULL" json:"title"`                                   // 标题
	Imgs     string    `gorm:"column:imgs;NOT NULL" json:"imgs"`                                     // 图片
	Content  string    `gorm:"column:content;NOT NULL" json:"content"`                               // 内容
	Status   int       `gorm:"column:status;default:0;NOT NULL" json:"status"`                       // 状态,0 待审核，10，审核完成，20 仅自己可见，100 删除
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *Feed) TableName() string {
	return "t_feed"
}

