// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 动态投票表
type FeedVote struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	FeedID   uint64    `gorm:"column:feed_id;default:0;NOT NULL" json:"feed_id"`                     // feedid
	Name     string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 选项
	Votes    uint      `gorm:"column:votes;default:0;NOT NULL" json:"votes"`                         // 投票人数
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *FeedVote) TableName() string {
	return "t_feed_vote"
}

