// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 动态投票表
type FeedVoteLog struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	FeedID   uint64    `gorm:"column:feed_id;default:0;NOT NULL" json:"feed_id"`                     // feedid
	UserID   uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 发布人ID
	ItemID   uint64    `gorm:"column:item_id;default:0;NOT NULL" json:"item_id"`                     // 投票选项id
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *FeedVoteLog) TableName() string {
	return "t_feed_vote_log"
}

