// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 标签
type Tags struct {
	ID         uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	TargetType uint      `gorm:"column:target_type;default:0;NOT NULL" json:"target_type"`             // 类型
	Name       string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 名称
	Logo       string    `gorm:"column:logo;NOT NULL" json:"logo"`                                     // LOGO
	BgColor    string    `gorm:"column:bg_color;NOT NULL" json:"bg_color"`                             // 背景颜色
	FontColor  string    `gorm:"column:font_color;NOT NULL" json:"font_color"`                         // 字体颜色
	SumTimes   uint      `gorm:"column:sum_times;default:0;NOT NULL" json:"sum_times"`                 // 次数
	CreateAt   time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP   string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt   time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP   string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *Tags) TableName() string {
	return "t_tags"
}

