// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 抽奖日志
type LotteryLog struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	LotteryID uint64    `gorm:"column:lottery_id;default:0;NOT NULL" json:"lottery_id"`               // 抽奖ID
	UserID    uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 用户ID
	ItemID    uint64    `gorm:"column:item_id;default:0;NOT NULL" json:"item_id"`                     // 中奖选项ID
	Day       *time.Time `gorm:"column:day;NOT NULL" json:"day"`                                       // 日期
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *LotteryLog) TableName() string {
	return "t_lottery_log"
}

