// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 抽奖信息
type Lottery struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Name     string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 抽奖活动名称
	Logo     string    `gorm:"column:logo;NOT NULL" json:"logo"`                                     // logo
	Kind     int       `gorm:"column:kind;default:10;NOT NULL" json:"kind"`                          // 类型，10轮盘抽奖
	DayLimit int       `gorm:"column:day_limit;default:0;NOT NULL" json:"day_limit"`                 // 每日限制次数，0无限制
	IsOpen   int       `gorm:"column:is_open;default:0;NOT NULL" json:"is_open"`                     // 是否开启
	Content  string    `gorm:"column:content" json:"content"`                                        // 描述
	CreateAt time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *Lottery) TableName() string {
	return "t_lottery"
}

