// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 抽奖配置
type LotteryItem struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	LotteryID uint64    `gorm:"column:lottery_id;default:0;NOT NULL" json:"lottery_id"`               // 抽奖ID
	Name      string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 选项名称
	Logo      string    `gorm:"column:logo;NOT NULL" json:"logo"`                                     // 图片
	Content   string    `gorm:"column:content;NOT NULL" json:"content"`                               // 描述
	Rate      int       `gorm:"column:rate;default:0;NOT NULL" json:"rate"`                           // 中奖概率
	IsOnline  int       `gorm:"column:is_online;default:0;NOT NULL" json:"is_online"`                 // 是否开启
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *LotteryItem) TableName() string {
	return "t_lottery_item"
}

