// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 商城品牌
type MallBrand struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Name      string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 品牌名称
	Logo      string    `gorm:"column:logo;NOT NULL" json:"logo"`                                     // 品牌LOGO
	More      string    `gorm:"column:more;NOT NULL" json:"more"`                                     // 品牌描述
	FirstChar string    `gorm:"column:first_char;NOT NULL" json:"first_char"`                         // 首字符
	IsShow    int       `gorm:"column:is_show;default:0;NOT NULL" json:"is_show"`                     // 是否显示
	CreateAt  time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MallBrand) TableName() string {
	return "t_mall_brand"
}

