// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 商城分类表
type MallCategory struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Name      string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 分类名称
	ParentID  uint64    `gorm:"column:parent_id;default:0;NOT NULL" json:"parent_id"`                 // 父分类ID
	Logo      string    `gorm:"column:logo;NOT NULL" json:"logo"`                                     // 图标
	IsShow    int       `gorm:"column:is_show;default:0;NOT NULL" json:"is_show"`                     // 是否显示
	SortIndex int       `gorm:"column:sort_index;default:0;NOT NULL" json:"sort_index"`               // 排序
	CreateAt  time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MallCategory) TableName() string {
	return "t_mall_category"
}

