// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 商城运费规则表
type MallFreight struct {
	ID              uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Name            string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 运费规则名称
	IsFree          int       `gorm:"column:is_free;default:0;NOT NULL" json:"is_free"`                     // 是否包邮
	DefaultPrice    uint      `gorm:"column:default_price;default:0;NOT NULL" json:"default_price"`         // 默认运费
	DefaultNum      uint      `gorm:"column:default_num;default:1;NOT NULL" json:"default_num"`             // 默认数量
	OverPrice       uint      `gorm:"column:over_price;default:0;NOT NULL" json:"over_price"`               // 超出运费
	OverNum         uint      `gorm:"column:over_num;default:1;NOT NULL" json:"over_num"`                   // 超出数量
	Forbid          string    `gorm:"column:forbid;NOT NULL" json:"forbid"`                                 // 禁运地区
	Excluding       string    `gorm:"column:excluding;NOT NULL" json:"excluding"`                           // 例外运费
	ExcludPrice     uint      `gorm:"column:exclud_price;default:0;NOT NULL" json:"exclud_price"`           // 默认运费
	ExcludNum       uint      `gorm:"column:exclud_num;default:1;NOT NULL" json:"exclud_num"`               // 默认数量
	ExcludOverPrice uint      `gorm:"column:exclud_over_price;default:0;NOT NULL" json:"exclud_over_price"` // 超出运费
	ExcludOverNum   uint      `gorm:"column:exclud_over_num;default:1;NOT NULL" json:"exclud_over_num"`     // 超出数量
	CreateAt        time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP        string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt        time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP        string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MallFreight) TableName() string {
	return "t_mall_freight"
}

