// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 商城商品表
type MallGoodsSpec struct {
	ID          uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	GoodsID     uint64    `gorm:"column:goods_id;default:0;NOT NULL" json:"goods_id"`                   // 商品ID
	Logo        string    `gorm:"column:logo;NOT NULL" json:"logo"`                                     // 规格图片
	ItemKey     string    `gorm:"column:item_key;NOT NULL" json:"item_key"`                             // 规格ID,_分隔
	ItemName    string    `gorm:"column:item_name;NOT NULL" json:"item_name"`                           // 规格名称
	MarketPrice uint      `gorm:"column:market_price;default:0;NOT NULL" json:"market_price"`           // 市场价
	SellPrice   uint      `gorm:"column:sell_price;default:0;NOT NULL" json:"sell_price"`               // 售价
	CostPrice   uint      `gorm:"column:cost_price;default:0;NOT NULL" json:"cost_price"`               // 成本价
	Stock       uint      `gorm:"column:stock;default:0;NOT NULL" json:"stock"`                         // 库存
	Sales       uint      `gorm:"column:sales;default:0;NOT NULL" json:"sales"`                         // 销量
	CreateAt    time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP    string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt    time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP    string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MallGoodsSpec) TableName() string {
	return "t_mall_goods_spec"
}

