// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 商城商品表
type MallGoods struct {
	ID          uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Name        string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 商品名字
	BrandID     uint64    `gorm:"column:brand_id;default:0;NOT NULL" json:"brand_id"`                   // 品牌ID
	CateID1     uint64    `gorm:"column:cate_id1;default:0;NOT NULL" json:"cate_id1"`                   // 一级分类ID
	CateID2     uint64    `gorm:"column:cate_id2;default:0;NOT NULL" json:"cate_id2"`                   // 二级分类ID
	CateID3     uint64    `gorm:"column:cate_id3;default:0;NOT NULL" json:"cate_id3"`                   // 三级分类ID
	FreightID   uint64    `gorm:"column:freight_id;default:0;NOT NULL" json:"freight_id"`               // 运费规则ID
	SpecID      uint64    `gorm:"column:spec_id;default:0;NOT NULL" json:"spec_id"`                     // 规格ID
	Sales       uint      `gorm:"column:sales;default:0;NOT NULL" json:"sales"`                         // 销量
	MarketPrice uint      `gorm:"column:market_price;default:0;NOT NULL" json:"market_price"`           // 市场价
	SellPrice   uint      `gorm:"column:sell_price;default:0;NOT NULL" json:"sell_price"`               // 售价
	CostPrice   uint      `gorm:"column:cost_price;default:0;NOT NULL" json:"cost_price"`               // 成本价
	Stock       uint      `gorm:"column:stock;default:0;NOT NULL" json:"stock"`                         // 库存
	IsOnlone    int       `gorm:"column:is_onlone;default:0;NOT NULL" json:"is_onlone"`                 // 是否上架
	Imgs        string    `gorm:"column:imgs;NOT NULL" json:"imgs"`                                     // 图片
	Detail      string    `gorm:"column:detail;NOT NULL" json:"detail"`                                 // 商品描述
	CreateAt    time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP    string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt    time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP    string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MallGoods) TableName() string {
	return "t_mall_goods"
}

