// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 商城规格表
type MallSpec struct {
	ID       uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Name     string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 名称
	RootID   uint64    `gorm:"column:root_id;default:0;NOT NULL" json:"root_id"`                     // 根ID
	ParentID uint64    `gorm:"column:parent_id;default:0;NOT NULL" json:"parent_id"`                 // 父ID
	CreateAt time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *MallSpec) TableName() string {
	return "t_mall_spec"
}

