// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 友情链接表
type FriendLinks struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Name      string    `gorm:"column:name;NOT NULL" json:"name"`                                     // 名称
	LinkType  string    `gorm:"column:link_type;default:WEB;NOT NULL" json:"link_type"`               // 类型：网站，app等
	Logo      string    `gorm:"column:logo;NOT NULL" json:"logo"`                                     // logo
	Url       string    `gorm:"column:url;NOT NULL" json:"url"`                                       // 地址
	Ios       string    `gorm:"column:ios;NOT NULL" json:"ios"`                                       // ios下载地址
	GooglePay string    `gorm:"column:google_pay;NOT NULL" json:"google_pay"`                         // googlepaly 地址
	BgImg     string    `gorm:"column:bg_img;NOT NULL" json:"bg_img"`                                 // 背景地址
	Content   string    `gorm:"column:content;NOT NULL" json:"content"`                               // 描述
	IsShow    int       `gorm:"column:is_show;default:0;NOT NULL" json:"is_show"`                     // 是否展示
	SortIndex int       `gorm:"column:sort_index;default:0;NOT NULL" json:"sort_index"`               // 排序
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *FriendLinks) TableName() string {
	return "t_friend_links"
}

