// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 管理员用户
type AdminUser struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	LoginName string    `gorm:"column:login_name;NOT NULL" json:"login_name"`                         // 登录名称
	NickName  string    `gorm:"column:nick_name;NOT NULL" json:"nick_name"`                           // 昵称
	Passwd    string    `gorm:"column:passwd;NOT NULL" json:"passwd"`                                 // 密码
	PassSign  string    `gorm:"column:pass_sign;NOT NULL" json:"pass_sign"`                           // 密码加盐
	TfaKey    string    `gorm:"column:tfa_key;NOT NULL" json:"tfa_key"`                               // 二次验证码key
	Status    int       `gorm:"column:status;default:0;NOT NULL" json:"status"`                       // 状态：100删除，90禁止登录
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *AdminUser) TableName() string {
	return "t_admin_user"
}

