// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 用户收货地址
type UserAddr struct {
	ID        uint64    `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	UserID    uint64    `gorm:"column:user_id;default:0;NOT NULL" json:"user_id"`                     // 用户ID
	Mobile    string    `gorm:"column:mobile;NOT NULL" json:"mobile"`                                 // 手机
	Consignee string    `gorm:"column:consignee;NOT NULL" json:"consignee"`                           // 收货人
	Province  string    `gorm:"column:province;default:0;NOT NULL" json:"province"`                   // 省份
	City      string    `gorm:"column:city;default:0;NOT NULL" json:"city"`                           // 城市
	District  string    `gorm:"column:district;default:0;NOT NULL" json:"district"`                   // 地区
	Address   string    `gorm:"column:address;NOT NULL" json:"address"`                               // 地址
	IsDefault int       `gorm:"column:is_default;default:0" json:"is_default"`                        // 默认收货地址
	CreateAt  time.Time `gorm:"->;column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"` // 创建时间
	CreateIP  string    `gorm:"column:create_ip;NOT NULL" json:"create_ip"`                           // 创建IP
	UpdateAt  time.Time `gorm:"->;column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"` // 更新时间
	UpdateIP  string    `gorm:"column:update_ip;NOT NULL" json:"update_ip"`                           // 更新IP
}

func (m *UserAddr) TableName() string {
	return "t_user_addr"
}

